### ISSUE TITLE
ProtocolLib - Removed on server startup

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1002]
As soon as I try to run this plugin Mohist creates a Deleted folder where it transfers this plugin! Its work is very important for many other plugins!

**Comment by ghost** [comment]
![e6f8a4b5888414a0f7165d437909ef2cc3bfaee1](https://user-images.githubusercontent.com/71688822/109628416-c6a2eb80-7b53-11eb-98ba-6d27b43f88cc.gif)

**Comment by Shawiizz** [comment]
That's normal. If you want you can report the plugin incompatibility by following the issue template in another issue. Thanks :)

**Comment by KR33PYK1NG** [comment]
ProtocolLib is fully broken now - even if we remove the auto-deletion it won't function properly.

**Comment by ghost** [comment]
sad

**Comment by laboriens** [comment]
I explain why they blocked protocolLib, because it's full of bugs but also if a user enter on a mohist 1.16.5 server with protocollib, the user is automatically disconnected from the server with an error as a reason so if mohist would have let the possibility to install protocolLib well your server will never connect on it even you in op you can't connect for that they put in mohist the auto del of the protocolLib plugins because they can't do anything (several ticket are open on this subject at ProtocolLib)

Translated with www.DeepL.com/Translator (free version)
