### ISSUE TITLE
Chisel and Bits sawed blocks disappearing

### ISSUE THREAD

**Issue by JosephRobbins17** [Teneted/Tenet#1010]
I have found that when installing chisel and bits (version 0.2.10) on a mohist server (have tried versions 380 and 381), the blocks created from sawing other blocks e.g. vertical slabs, pillars, panels etc. disappear immediately after placing them, as if the client has the mod but the server does not. The mod works fine in single player and on forge servers. I have also tried rebuilding a new mohist 381 server with no other mods or plugins and encountered the same issue. Other features of the mod like chiselling bits out of blocks and placing them back down work fine.

https://user-images.githubusercontent.com/76403412/109794833-2d84db00-7c0e-11eb-85cd-f490ddf04f9e.mp4

**Comment by ghost** [comment]
A similar problem! I agree!

**Comment by cookta2012** [comment]
What is actually happening is the event to place the block is being either triggered or not triggered the item is still in your inventory it has something to do with I guess NBT data because more than one mod has had problems even with the newest version with NBT data like there are some items you can place inside a Applied Entergistics system that you can't pull out. And it's with any chiseled block The bits work fine it's just any chiseled block that's in the inventory you go to place it as a player it will not place.

**Comment by cookta2012** [comment]
I'm going to be clear when I say the newest version I mean any version all the way up through the newest version

**Comment by cookta2012** [comment]
Also there is nothing generated in the console with regards to that.

**Comment by cookta2012** [comment]
Console on client is throwing 
https://mcpaste.io/7a5b0906eb19ce19
