### ISSUE TITLE
TPS with Pixelmon 

### ISSUE THREAD

**Issue by LoopRich161** [Teneted/Tenet#151]
Hello, i have server with pixelmon (version pixelmon 7.2.0).
When there are 5 people on my server, then my TPS is 18-20
When there are 15 people on my server, then my TPS is 7-18
I would like to know what the problem is. Below I enclose a list of mods and plugins.
Server core: Mohist-9d300c6

I did not write all the libraries needed for mods. I think this makes no sense
Mods on the server:
MoveSkillController-1.12.2-1.0.3.jar
EvenMorePixelmonCommands-1.12.2-5.1.1.jar
PixelHunt-1.1.3-MC1.12.2-S7.2.0.jar
InGameConfigManager.jar
TCG-1.12.2-4.0.1.jar
CS-betterfps-1.4.8.jar
Pixelmon-1.12.2-7.2.0.jar
ironchest-1.12.2-7.0.72.847.jar
CoralReef-2.5-1.12.2.jar
CTM-MC1.12.2-1.0.1.30.jar
EnderBags-1.12.2-2.1.0.jar
PixelExtras-1.12.2-2.5.4.jar
SimpleDexRewards-1.0-RELEASE-.jar
Chameleon-1.12-4.1.3.jar
LegendaryPlus-5.1.2.jar
StorageDrawers-1.12.2-5.4.0.jar
Gameshark-1.12.2-6.0.3.jar
furniture-6.3.1-1.12.2.jar
PixelAuction-1.12.2-1.1.4.jar
EcoBridge-1.12.2-2.0.7.jar
Mantle-1.12-1.3.3.55.jar
onlinepicframe.jar
PixelmonBroadcasts-1.12.2-0.4.1.jar
TreeCapitator.jar
EssentialFeatures.jar
bonsaitrees-1.1.4-b170.jar
Chisel-MC1.12.2-1.0.1.44.jar
MTLib306.jar
OpenFM.jar
creativecore.jar
WonderTrade-1.12.2-4.6.2.jar
Tournaments-1.12.2-2.6.2.jar
ElevatorMod-1.12.2-1.3.14.jar

Plugins:
WorldGuard
MultiWorld
MaxBans (Using MySQL)
AdvancedRandomTeleport
VoxelSniper
PermissionsEx
Vault
BanItem
MyCommand
PlaceholderAPI
MyWarp
EssentialsX
EssentialsXChat
EssentialsXSpawn
TAB
Protocolib
WorldEdit
WorldBorder
iConomy
CoreProtect
ClearLag

**Comment by CraftDream** [comment]
I don't think it's a issue, it's an optimization.
You need to optimize the Server, from the physical tick, sight distance, tracking distance and so on (bukkit.yml, paper.yml, spigot.yml, mohist.yml...)
Mohist will try to provide a part of performance optimization (multithreading?) But it's up to you.
You can use Timing, Spark and other performance analysis tools to analyze the causes of Caton.
Pixelmon is also a very performance consuming mod, because it has a large number of entities and their AI, so Carton is not the reason for Mohist.
So you want to keep the TPS 19-20 in the case of many players and entities. That's ridiculous. At least when you run Pixelmon. Don't ask me why, because I'm also a Server Master of a Pixelmon's Server.

**Comment by LoopRich161** [comment]
I didn’t think so. I agree, close
