### ISSUE TITLE
[1.16.5] Generation bug

### ISSUE THREAD

**Issue by MrJorman** [Teneted/Tenet#1511]
i use abnormals mods.. and world generating... PLS FIX BRO! no crash log
![image](https://user-images.githubusercontent.com/55187962/124720111-76c49e80-df10-11eb-9d5b-eb026fa482fb.png)

**Comment by KR33PYK1NG** [comment]
Can't reproduce, using Abnormals Mods myself.

**Comment by GitJhopa** [comment]
Minecraft Version: 1.16.5
Build: tested all builds#650-#701
Logs: NONE
Mods: screen
Plugins: screen
BUG: SEE SCREEN!

Please, please! Finally fix the bugs of custom generation! My world generation costs new biomes from Abnormals, my friends have BiomesOplenty, we have very big bugs of map generation, it is after the server reboot that it is not a single one, we use the latest versions of the kernel and used different ones and tested, Your kernel breaks chunks of custom generation! Please, I beg you, fix this case! It's impossible to play! All chunks are broken - the map is terrible, vanilla chunks - good ones do not break, any mod that adds custom generation - chunks break!
![image](https://user-images.githubusercontent.com/86250668/125177576-9d6f2780-e1e5-11eb-9c45-7b91c93e1c9a.png)
![image](https://user-images.githubusercontent.com/86250668/125177581-a52ecc00-e1e5-11eb-9938-976bf9d8b8ab.png)
https://user-images.githubusercontent.com/86250668/125177492-dd81da80-e1e4-11eb-80bb-856785567620.png
![image](https://user-images.githubusercontent.com/86250668/125177587-aa8c1680-e1e5-11eb-8147-d52b99f440f5.png)
![image](https://user-images.githubusercontent.com/86250668/125177589-ac55da00-e1e5-11eb-8ca9-5fd76cfd6f55.png)
![image](https://user-images.githubusercontent.com/86250668/125177590-aeb83400-e1e5-11eb-9499-c042a3c9b688.png)
![image](https://user-images.githubusercontent.com/86250668/125177593-b081f780-e1e5-11eb-8390-44122a66ad87.png)

When I used a clean forge or a single world, there were no problems! This problem is observed only on Mohist! And not just me!

**Comment by GitJhopa** [comment]
The chunk bug does not appear immediately, you need to make several restarts and fly around the map and you will eventually be able to find a lot of badly broken chunks, oddly enough, but they restore the usual (correct) biome using the WorldEdit command / / regen

**Comment by GitJhopa** [comment]
The bug is real, it has already been stored with me for about 50 days. I'm tired of making a new map for players, since all maps come with broken chunks if they have mods for the new generation.

**Comment by GitJhopa** [comment]
There are no errors in the console in this case. But this is a really, very important problem with generation, it should not generate individual pieces of biomes like this. I've already checked everything, I've tested it without plugins, without unnecessary mods - it doesn't matter, everything that adds custom generation - everything bugs.

**Comment by GitJhopa** [comment]
This error manifests itself on fresh fragments that have not yet been uploaded in advance.

**Comment by MrJorman** [comment]
yes++ the same problem

**Comment by GitJhopa** [comment]
I noticed a bug that may help you understand the essence, if I put the sid of the world 12345 for example, then the biome "dunes" from Abnormals Mod will spawn next to me, I fly a little further, the biome "cherry forest" will spawn, but if I delete the map and do the generation of the same sid, other biomes already appear in this place, instead of "dunes" there is already a swamp from Abnormals Mods, it feels like chunks break when I restart the server and at some point just there is an overlap of biomes already on the finished biome, that's the point. After all, when I write on a broken chunk / / regen, the biome that was at 1 side is restored.

**Comment by GitJhopa** [comment]
You can hardly repeat this bug quickly, so it took me 3 game days for the players to play and find this broken chunk, but sometimes they happen right after creating the map and restarting the server. I also always set /worldborder set { }, maybe it breaks them, I don't know..

**Comment by GitJhopa** [comment]
Also, these broken chunks are on my friend's server, he uses BiomesOPlenty.

Please correct this and fix the error, this is probably the toughest mistake that breaks the world with custom generation.

**Comment by GitJhopa** [comment]
I just created a clean map on the last build of Mohist, and as a result I wrote 
1. /worldborder center ~ ~
2. /worldborder set 10000
3. /stop
4. Start the server right now..
5. /gamemode 1
6. I fly around the map and load the pieces for about 1 minutes.
7. /stop
8. Start the server right now..
9. I fly around the map and load the pieces for about 5-10 minutes.
10. As soon as I entered, literally 30 seconds flew by and immediately next to my appearance I found a new broken chunk that had not been loaded before.
11. Sometimes you need to restart the server 2-4 times.
![image](https://user-images.githubusercontent.com/86250668/125178550-f1323e80-e1ee-11eb-8cca-2ebc5a67a7c3.png)
![image](https://user-images.githubusercontent.com/86250668/125178554-f68f8900-e1ee-11eb-9f0f-e423d8f4674a.png)
![image](https://user-images.githubusercontent.com/86250668/125178556-fabba680-e1ee-11eb-88e6-af87e8b92440.png)
![image](https://user-images.githubusercontent.com/86250668/125178558-04450e80-e1ef-11eb-9661-903102b9f941.png)
![image](https://user-images.githubusercontent.com/86250668/125178565-0d35e000-e1ef-11eb-9bb8-25bc0395fc12.png)

**Comment by GitJhopa** [comment]
![image](https://user-images.githubusercontent.com/86250668/125179115-ea59fa80-e1f3-11eb-8df0-45e6a218d01f.png)
Here is another bug, I repeated the actions in the same way:)

**Comment by GitJhopa** [comment]
I have a suspicion that this is a NetherPortalFix+WorldEdit mod, I have players with them taking damage when they entered the portal to HELL.. I removed NetherPortalFix and nothing happens again.

**Comment by GitJhopa** [comment]
You say me ?

**Comment by Romaindu35** [comment]
> You say me ?

?

**Comment by Romaindu35** [comment]
Are you add mods after create world ?

**Comment by GitJhopa** [comment]
No

**Comment by GitJhopa** [comment]
check the bug yourself, if you don’t believe me, I dropped the mods above, and the action plan too, sometimes it doesn’t work just once - but there are restarts on the server, so the bug is always there.

**Comment by GitJhopa** [comment]
checked on a clean Forge server and rebooted - everything was fine.

**Comment by MrJorman** [comment]
Please fix this bug, I have already made 12 vips of my card on the server, my players are very angry and leave the project because of these chunks. The bug is real and it exists, please check it!

**Comment by Romaindu35** [comment]
We also have a privacy, we are not available all the time, so if you want the bug fixed quickly you do it yourself or you pay someone to do it else you just wait!

**Comment by MrJorman** [comment]
I would pay you for your help, but at the moment the kernel does not allow me to collect donat, since I can't make the server stable! Make the chunks a high priority and fix them, then I will be able to thank you with a certain amount from the players ' donations.

**Comment by MrJorman** [comment]
please fix it.

**Comment by Shawiizz** [comment]
Hello, know that we are working on our free time and that we have lives. So please be patient.

**Comment by MrJorman** [comment]
please fix it, my server still can't work normally..

**Comment by GitJhopa** [comment]
fixed. i download broken mods..

**Comment by Romaindu35** [comment]
Si, It is mod problem or mohist problem. And what mod is broken ?

**Comment by MrJorman** [comment]
mod problem.

**Comment by Romaindu35** [comment]
So I can close ?

**Comment by Romaindu35** [comment]
So I can close ?

**Comment by joaoespanhol** [comment]
being a mod problem, not mohist, close the ticket please.
@Romaindu35
