### ISSUE TITLE
Optimizations please

### ISSUE THREAD

**Issue by neptune-gaming** [Teneted/Tenet#1683]
**Is your feature request related to a problem? Please describe.**
Mohist is a little bit laggy even on good hardware. It crashes once in a while for me and my friends because of lag.

**Describe the solution you'd like**
It would be nice to mix Mohist with Tuinity, Purpur, or AirplaneMC.

**Additional context**
None that i could add.

**Comment by wdog5** [comment]
We must do the compat for mods and plugins instead of doing this，please keep waiting

**Comment by Shawiizz** [comment]
This can't be done at all. Mohist 1.16.5 isn't stable enough and we don't plan to implement any of these patches because this would create a lot of incompatibilities. If you really want these patches to be implemented, i think you can wait more than 6 months, since first Mohist 1.16.5 needs to be more stable and this would take a lot of time. 
By the way, if you need a Mohist 1.16.5 with some Paper patches, i recommend you to use [Mist](https://github.com/MinecraftMist/Mist).
Have a nice day!
