### ISSUE TITLE
Server is dead (TPS = 1 - 5!!!)

### ISSUE THREAD

**Issue by GDVE** [Teneted/Tenet#176]
https://sparkprofiler.github.io/#XuE2hCclON

https://github.com/Mohist-Community/Mohist/issues/169 - server info is here!

**Comment by ProsperCraft** [comment]
We had to set up a script to run clearlags lagg unloadchunks on a regular basis because they never unload.  When it unloads it can unload 20-30k chunks at a time which has a massive impact on server performance.  Before we figured that out we had to reboot every two hours.

Modpack- https://www.curseforge.com/minecraft/modpacks/towncraft
