### ISSUE TITLE
classyhats mod - Bad type on operand stack

### ISSUE THREAD

**Issue by thejbone** [Teneted/Tenet#1912]
**Minecraft Version :** 1.12.2

**Mohist Version :** Mohist version 1.12.2-290 (MC: 1.12.2)

**Operating System :** Linux:amd64:4.19.0-18-amd64 jre1.8.0_311

**Logs :** https://haste.mohistmc.com/vipuyuwegi.yaml

**Mod list :** https://haste.mohistmc.com/baloxepuqi

**Plugin list :** None

**Description of issue :**  When running ClassyHats mod, with only it and its dependencies, if you login with a client with the same mods, the server times out the client as it hangs on an error. 

`java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/network/NetHandlerPlayServer.func_147340_a(Lnet/minecraft/network/play/client/CPacketUseEntity;)V @350: invokeinterface
  Reason:
    Type 'java/lang/Object' (current frame, stack[1]) is not assignable to 'org/bukkit/event/Event'`

**Comment by Charles445** [comment]
This is caused by LibrarianLib using a transformer that computes frames on NetHandlerPlayServer, setting any unknown common super classes as java/lang/Object, so the frames get corrupted when it sees bukkit event classes.
https://github.com/TeamWizardry/LibrarianLib/blob/1.12/src/main/java/com/teamwizardry/librarianlib/asm/LibLibTransformer.java#L772-L775

I don't think this is something Mohist can fix, as it's going to happen on other bukkit implementations too. 
I believe the right course of action would be to have LibrarianLib rewrite their transformers to either avoid the need for computing frames entirely (all hooks, no jumps) or use a safer class writer like Evil Notch Lib (or anything that uses Eric Bruneton's ComputeClassWriter really)
