### ISSUE TITLE
Mohist was flagged as malicious

### ISSUE THREAD

**Issue by uttxms** [Teneted/Tenet#2341]
**What is your question ?**
I ran the Mohist jar file on VirusTotal and it detected a trojan.

[LINK TO SCAN](https://www.virustotal.com/gui/file/4fb70895ff4a1fc301141e4d3d9fdc703135e6b371c00079be8e19b93a8b13ca)

Is this a common error or is this a serious problem?

**Comment by Shawiizz** [comment]
Hello, it's a false positive, nothing to worry about. 

I have already sent an email to Google to fix the problem with their AV, and hope to get an answer soon.

About the other AV, i just believe it's not really reliable AV and we can't do anything so that it won't detect Mohist as malicious anymore unfortunately.
