### ISSUE TITLE
Make a compliant Bukkit API implementation and remove the Plugin Checker

### ISSUE THREAD

**Issue by r1sk01** [Teneted/Tenet#2368]
**Is your feature request related to a problem? Please describe.**
Yes, the Bukkit API is heavily broken when I run one of my server plugins on Mohist, but on Spigot and Paper, it works fine, due to your non-compliant Bukkit API implementation.

**Describe the solution you'd like**
Make a compliant Bukkit API implementation and stop thinking that making users download arbitrary code from an unknown source is going to fix it all disguising it as a "plugin checker", it's dangerous and we developers know it can be modified to download malware onto servers.
**STOP AND FIX IT**

**Additional context**
[EssentialsX and their PSA on it](https://essentialsx.net/do-not-use-mohist.html)

**Comment by Shawiizz** [comment]
Hello, thanks for opening an issue.

First, please know that making an hybrid server software is not as easy as you think, there will always be incompatibilities, and we know it.

The plugin checker **is not dangerous** at all, and there's no malware. Everyone can check it by himself just by looking **at the modified plugins source code** :smile: 
The difficulty of fixing plugins is still there as there are **not always many solutions**, and fixing Mohist incompatibilities that makes some plugins not working correctly **isn't an easy process**. To overcome this problem **temporarily** so as not to leave our users without functional plugins the time we think about a way to fix it, we have created this system.

I see you pointed to the PSA from EssentialsX, which **is not a reliable source**. I recommend you in the future to **check your sources**, because some are not reliable, **including EssentialsX** in this case. [Here is our official answer](https://github.com/Shawiizz/MohistEssentialsX/blob/main/README.md) on EssentialsX's PSA. If you could please read it, it will help you to understand what is true and what is false, and therefore to understand that almost all of the information given by EssentialsX on Mohist is **false and outdated**.

I'd like to add that if you haven't already, you can open a github issue if one of your plugins doesn't work with Mohist.

I remain at your disposal if necessary.

**Comment by Soapy7261** [comment]
Mohist has fixed this issue about a year ago, also, the plugin checker was not clear because nobody in the mohist team natively speaks english, so don't bash them too hard
By the way, the plugin it downloaded was on github, you can see that in the source code, and you can see the github page it downloaded from if you wish

**Comment by r1sk01** [comment]
> 

I see, I will try to find a workaround on the whole thing, I had found this a while ago and was really mad considering it'd seemed like it was intentional (I assumed the person who made it spoke English as their first language), adding a few details about that would've helped, however I couldn't find the info on the languages the team spoke.
Thank you, I will look into finding a workaround with the replacing the player on death.
Nova
