### ISSUE TITLE
Mohist for 1.8?

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#2432]
**Is your feature request related to a problem? Please describe.**
Yes, I noticed that Mohist supports only 1.7 1.12 1.16 and 1.19 but not 1.8 which is strange since Mohist supports 1.7

**Describe the solution you'd like**
If Mohist could have 1.8 support.

**Additional context**
I know that 1.8 added new stuff like spectator and some new blocks so I understand if you all at the team do not feel like putting time into this.

**Comment by Shawiizz** [comment]
Hello,
To answer you quickly, it's a no. There are two reasons:
- Mohist 1.7.10 support has been dropped since a few years
- We don't have enough time and developers to maintain such versions

We would like to build Mohist for more versions but before doing that, we have to stabilize existing versions (which is quite hard) and also taking a few years to do. We're also focusing on latest minecraft versions so that's why we do not necessarily work with older ones.
If you have any question you can still write there.
