### ISSUE TITLE
Server "crash" with >Killed but there isn't any crash log.

### ISSUE THREAD

**Issue by Lunyyx** [Teneted/Tenet#282]
Hello, I've a little problem with my server...

**Describe the bug**
My Mohist server get >Killed at random moments, sometimes it's when the server starts, or sometimes it's while playing. 

**To Reproduce**
There isn't any steps to reproduce, because the server crash at fully random times.

**Screenshots**
https://imgur.com/a/F65U6Uo

**Info (please complete the following information):**
- Mod/Plugins Name: 
Mods: https://pastebin.com/yTVkW5N3 (Too much to list here)
Plugins:
Clearlag.jar
IPLock.jar
SkinsRestorer.jar

- Mod/Plugins Version: They're all at the last version.

**Additional context**
I already tried to update all mods at the last version, I tried to change the number of ram allowed for the server. But nothing.

------------

**EDIT/POSSIBLE SOLUTION FOR YOU:** Error solved by rebooting the machine.

**Comment by Shawiizz** [comment]
Hello, this is caused by your machine/server, not Mohist.  (maybe too mods and plugins for not enough ram)

**Comment by Shawiizz** [comment]
Try to allow more ram to your server

**Comment by Lunyyx** [comment]
> Try to allow more ram to your server

Hello, thanks for the fast reply, I've already tried 8, 10 and 12GB without succes, maybe I need more ?

**Comment by Shawiizz** [comment]
Yeah maybe. But it can also be caused by that your processor isn't capable to support your server. But i think one of your mod want a lot of ram. I never had to allow more than 8 gb of ram with a modpack with 200 mods. I can't really tell your the problem, but you maybe need to try on another machine or find which plugin / mod is taking a lot of ram.

**Comment by Lunyyx** [comment]
> Yeah maybe. But it can also be caused by that your processor isn't capable to support your server. But i think one of your mod want a lot of ram. I never had to allow more than 8 gb of ram with a modpack with 200 mods. I can't really tell your the problem, but you maybe need to try on another machine or find which plugin / mod is taking a lot of ram.

Is there any way to watch the memory using mod by mod, on the server or the client please (Like a certain plugin, a debug menu...) ?

**Comment by Shawiizz** [comment]
I don't know a good way to do that automatically, sorry :c

**Comment by Lunyyx** [comment]
> I don't know a good way to do that automatically, sorry :c

No problem, I will try to solve the problem by removing some mods or modifying some settings, thanks a lot :) 👍

**Comment by ishland** [comment]
This is caused by linux kernel. Because kernel realizes that there's no more ram or swap available and start randomly killing processes. Decreasing heap sizes may help. But you should get more RAM or add more swap to your system. 
If your ram and your swap is far more than enough, there may be some processes randomly killing programs. 

This issue is not related to Mohist.

**Comment by Lunyyx** [comment]
> This is caused by linux kernel. Because kernel realizes that there's no more ram or swap available and start randomly killing processes. Decreasing heap sizes may help. But you should get more RAM or add more swap to your system.
> If your ram and your swap is far more than enough, there may be some processes randomly killing programs.
> 
> This issue is not related to Mohist.

Hey, thanks to try to help me, my problem IS solved for now, for anyone who get this error in the future, try to reboot your machine :)
