### ISSUE TITLE
Debug stick works partially

### ISSUE THREAD

**Issue by kovalscky** [Teneted/Tenet#2830]
**Minecraft Version :** 1.19.4

**Mohist Version :** 189

**Operating System :** Linux

**Logs :** This issue does not cause crash reports or create information in server logs

**Mod list :** List of mods below:
![image](https://github.com/MohistMC/Mohist/assets/152068149/2c5dab95-6f85-4e0d-9f43-11a7515242eb)

**Plugin list :** List of plugins below:
![image](https://github.com/MohistMC/Mohist/assets/152068149/23652290-bdcd-4367-b90f-b579de605e64)

**Description of issue :** Debug stick gives an ability to edit only "up", "west", "north" blockstates of the wall and "waterlogged", "west", "north" blockstates of the fence. The "south", "east", "waterlogged" are unavailable. Player has server operator rights

**Steps to Reproduce :**
 1. Give yourself a debug stick via /give in game console or command block
 2. Place any wall block and try to edit it's blockstate with debug stick
 3. After wall place any fence and try to edit it's blockstate too
 4. You will see, that you will have all of the blockstates except "south", "east", "waterlogged" of wall's blockstates and "south", "east" of fence's blockstates

**Comment by Klime65536** [comment]
Still getting this on the current 1.20.1 build (514) with no plugins or mods installed, also tested build 500 (corresponding with https://github.com/MohistMC/Mohist/commit/481a834faa369d70b882db2d29b2b014b5b91d81) with the same results.
The "shape" blockstate on stairs, the "type" blockstate on slabs, the "facing" blockstate on ladders, and the "facing" and "open" blockstates on fence gates are also missing, otherwise the issue is the same as mentioned in the original report.
