### ISSUE TITLE
1.20.1 Coreprotect log spam

### ISSUE THREAD

**Issue by funnycubeguy** [Teneted/Tenet#3152]
Coreprotect log spam

https://pastes.dev/x17LLfvPJ0

**Comment by sanik** [comment]
@Mgazul The problem is that Container itself is null and not CraftCustomInventory, so this does not fix the error...

if (container != null)

Inventory sourceInventory = InventoryOwner.getInventory(container);

If you look at CraftCustomInventory in it

 public Location getLocation() {
 return inventory.getLocation();
 }
and inventory == null
