### ISSUE TITLE
[1.20.2] Pixelmon 9.2.8 incompatible with Spigot plugins (Class not found)

### ISSUE THREAD

**Issue by SimonMage00** [Teneted/Tenet#3213]
**Is your feature request related to a problem? Please describe.**
Yes, I have used Pixelmon Reforged 9.2.8 on my server and Spigot plugins spam an error when I join on my server where a class it's not found. https://mcpaste.io/ba77549264eeedb4

**Describe the solution you'd like**
Add the class and fix this bug please

**Additional context**
https://mcpaste.io/ba77549264eeedb4

**Comment by SimonMage00** [comment]
Also with Citizens
https://mcpaste.io/b8af6482395238ed

**Comment by Mgazul** [comment]
Pixelmon runs the client class in the server

**Comment by SimonMage00** [comment]
> Pixelmon runs the client class in the server

It can be fixed?

**Comment by JSHZT** [comment]
I also encountered this problem. I tried to use the server version and the client version of the pixelmon module, but when using the plugin, an error message saying that the class could not be found would appear. Currently, the plugins that report errors are all plugins for cleaning up dropped objects and entities. Is there any solution? Maybe this issue should remain open until the problem is solved.
