### ISSUE TITLE
Crash immediately on startup (not mod or plugin related)

### ISSUE THREAD

**Issue by KEEGUNATOR2** [Teneted/Tenet#3323]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {839}

**Operating System :** {Ubuntu 24.04 LTS}

**Logs :** {Latest.log:https://pastebin.com/UCqy53em   Server console: https://pastebin.com/emwKpTxL   }

Mohist is crashing immediately on startup. I cannot figure out the issue. I have removed all mods and plugins, didn't do anything. I have changed from Java 21 to 17, didn't work. I have downgraded to previous versions that worked, also didn't work. I don't know the cause.

Edit: Reverting the world file to an earlier backup had no affect either. Clearing the library folder, configs, and everything else also didn't work. It would load fine in a brand new installation though.

**Comment by DMONEYY008** [comment]
I think the problem is that you are using Linux. Windows is a more superior platform that may be better for servers because typically linux has a a lot of bloatware compared to Windows. If this doesn't work try restarting the server at least 2 times. It may also be because you are using weird plugins.

**Comment by KEEGUNATOR2** [comment]
This is still not resolved. Why did you close it?

**Comment by Mgazul** [comment]
Unable to reproduce
