### ISSUE TITLE
[1.20.1] Mythic Dungeons cave creature not suppoted 

### ISSUE THREAD

**Issue by Talan67** [Teneted/Tenet#3345]
**Minecraft Version :** 1.20.1

**Mohist Version :** 864

**Operating System :** Windows 10

**Concerned mod / plugin** : https://mythiccraft.io/index.php?resources/mythic-dungeons.869/

**Logs :** Debug: https://gist.github.com/Talan67/3d7cc6cb62eb4d53b506f0c4512d5118
                Latest: https://gist.github.com/Talan67/9dcf6d55ff1d08e2083ca79cdd285840

**Steps to Reproduce :**
 1. Install "Friends and Foes" or "Alex's Caves" and "Citadel" (I used both in this case because its the same issue)
 2. Join Server
 3. Create dungeon with "/md create <name> classic"
 4. Edit dungeon with "/md edit <name>"
 5. Error...

**Description of issue :** Dungeons cannot be loaded as the Mob "Glare" from "Friends and Foes" and all the Mobs from "Alex's Caves" have a special spawn category that is not present in Vanilla or Bukkit, which causes Mythic Dungeons to throw an error.

**Comment by Unitei-Dev** [comment]
the problem is in the Citadel engine, there's nothing to do about it, you need to either port Alex's Cave's mod to your engine or ask the author to do it. All modders have removed his dispenser from their mods (so that he doesn't fix it, you only have two options, either my suggested one, or recreate it yourself there is no other option in Mcreator and there will not be)

**Comment by Unitei-Dev** [comment]
The problem with Citadel is that it has the same function as in the Mythicdungers plugin

**Comment by Unitei-Dev** [comment]
And these are their generators and the launch of the world
