### ISSUE TITLE
When I enter the server it gives me this error

### ISSUE THREAD

**Issue by Teoxex** [Teneted/Tenet#677]
Hello everyone. When I try to enter the server it gives me this error: `Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (CConfirmTeleportPacket) was larger than I expected, found 11 bytes extra whilst reading packet 0`. The Discord Mohist Community told me it's a bug and I need to report it here. Do you know how to solve the problem?

**Comment by Mgazul** [comment]
Please provide a list of mods and plugins, as well as a complete log file.

**Comment by Teoxex** [comment]
I tried the server without mods or plugins to see how it worked

**Comment by X-Niter** [comment]
> I tried the server without mods or plugins to see how it worked

I've had this issue "The exact one", what ended up fixing it was changing any plugins to use YAML storage and not SQLite storage, I then deleted the SQLite.DB file that any of the plugins created and from there everything was good. 

I can't tell you which plugins would do it, just start going one by one and see if that fixes it. 
If it doesn't then it's something else, and that's the most help I could give.

**Comment by izushizuka** [comment]
Hello, I am also experiencing this kind of error. It would seem that the problem is happening because of ProtocolLib(?) as whenever I remove it from the plugins folder I can connect to the server just fine.

Here's a portion of the log when a player tries to connect with ProtocolLib(v4.6.0) debug on. Let me know if anything else is needed as this is my first time reporting an issue on Github. https://pastebin.com/36ZHc4h8
