### ISSUE TITLE
[1.12.2] Invalid move player packet received

### ISSUE THREAD

**Issue by GDVE** [Teneted/Tenet#74]
After flying at the elite, crashes with an error began: Invalid move player packet received

**Comment by Mgazul** [comment]
Unable to determine the problem

**Comment by GDVE** [comment]
The second way to repeat the bug is a scorpion in the world of Erebus (grabbed me and immediately teleported and kicked me out of the game with the same error)

**Comment by Avalkiz** [comment]
For me it happened sometimes when player jumped on Immersive Engineering wires. Player could later not join the server anymore because their last coordinates in playerdata file were changed to [NaN].
Manually changing the coordinates to something else fixed their ability to join the server and later disabling IE's cables feature to hurt players on touch prevented that from happening again.
