### ISSUE TITLE
Issue with StreamingDrops

### ISSUE THREAD

**Issue by CraftJunkies** [Teneted/Tenet#784]
Only happens mif StreamingDrops.jar is loaded. without it works
https://pastebin.com/WGxHVakY

**Comment by CraftJunkies** [comment]
If the StreamingDrops plugin is loaded, a random mod gives the error shown in the pastebin, mostly applied throws this error but if applied is deaktivated another mods throws the same error. I didnt try it without mods. Plugin works fine on spigot.jar.

**Comment by CraftJunkies** [comment]
Catserver has the same problem

**Comment by morelaid** [comment]
I am the developer of StreamingDrops and was able to find the named problem.

I have or will solve this from my side. The problem is in the structure of HTTPS requests. With the "Corn HTTP Client" these errors seem to appear. This was only put in to fix a bug with another plugin, but unfortunately this seems to be making waves.

For other developers:
If you use a different method for the HTTP connection, this will work. I do this by asking which HTTP connection or client is being used
